import { CLOUDINARY_IMG_PATH } from 'src/constants/paths';

export const VIVIENDA_BGM = [
	{
		id: 310,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808927/Vivienda_BGB/09_g2pckq.jpg`,
		label: 'bgm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 311,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808927/Vivienda_BGB/10_rp1d8c.jpg`,
		label: 'bgm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 312,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808927/Vivienda_BGB/08_g64pxm.jpg`,
		label: 'bgm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 313,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808926/Vivienda_BGB/07_m78hvf.jpg`,
		label: 'bgm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 314,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808926/Vivienda_BGB/01_kvgkhe.jpg`,
		label: 'bgm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 315,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808926/Vivienda_BGB/06_lhojqr.jpg`,
		label: 'bgm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 316,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808926/Vivienda_BGB/05_y4aurw.jpg`,
		label: 'bgm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 317,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808926/Vivienda_BGB/04_sfbomt.jpg`,
		label: 'bgm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 318,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808926/Vivienda_BGB/02_wbeowo.jpg`,
		label: 'bgm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 319,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808926/Vivienda_BGB/03_escagv.jpg`,
		label: 'bgm_house',
		description: '',
		linkTo: '',
	},
];
