import { CLOUDINARY_IMG_PATH } from 'src/constants/paths';

export const CONCURSO_AYUNTAMIENTO_ALBALAT = [
	{
		id: 1801,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721906194/Concurso_Ayuntamiento_Albalat/nwfxnk0fcxd9ieen0fxc.jpg`,
		label: 'concurso_ayuntamiento_albalat',
		description: '',
		linkTo: '',
	},
	{
		id: 1802,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721906210/Concurso_Ayuntamiento_Albalat/rbswwfoi76vravw45kwo.jpg`,
		label: 'concurso_ayuntamiento_albalat',
		description: '',
		linkTo: '',
	},
	{
		id: 1803,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721906193/Concurso_Ayuntamiento_Albalat/h1iqrkpm3tkjaknrv0zg.jpg`,
		label: 'concurso_ayuntamiento_albalat',
		description: '',
		linkTo: '',
	},
	{
		id: 1804,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721906220/Concurso_Ayuntamiento_Albalat/srlnoym2ucdb2hkywcmk.jpg`,
		label: 'concurso_ayuntamiento_albalat',
		description: '',
		linkTo: '',
	},
	{
		id: 1805,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721906359/Concurso_Ayuntamiento_Albalat/zhrxp756g0lv62rhlqhk.jpg`,
		label: 'concurso_ayuntamiento_albalat',
		description: '',
		linkTo: '',
	},
	{
		id: 1806,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721906355/Concurso_Ayuntamiento_Albalat/vwad3gpdwyjwtjxacmlf.jpg`,
		label: 'concurso_ayuntamiento_albalat',
		description: '',
		linkTo: '',
	},
	{
		id: 1807,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721906349/Concurso_Ayuntamiento_Albalat/ramkncev54w9g7upcj6j.jpg`,
		label: 'concurso_ayuntamiento_albalat',
		description: '',
		linkTo: '',
	},
	{
		id: 1808,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721906344/Concurso_Ayuntamiento_Albalat/bgtfugmw6mmmdhhp5wvs.jpg`,
		label: 'concurso_ayuntamiento_albalat',
		description: '',
		linkTo: '',
	},
	{
		id: 1809,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721906330/Concurso_Ayuntamiento_Albalat/saj2ucgqif6nbsiedpgu.jpg`,
		label: 'concurso_ayuntamiento_albalat',
		description: '',
		linkTo: '',
	},
];
