import { CLOUDINARY_IMG_PATH } from 'src/constants/paths';

export const OFICINAS_ALSACARGO = [
	{
		id: 90,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809636/Oficinas_Alsacargo/2_c2l5mv.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 91,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809626/Oficinas_Alsacargo/6_watx74.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 92,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809624/Oficinas_Alsacargo/21_najjlw.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 93,
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809623/Oficinas_Alsacargo/14_wnxhm5.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 94,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809623/Oficinas_Alsacargo/24_xmp0lb.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 95,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809623/Oficinas_Alsacargo/4_hw3xaw.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 96,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809623/Oficinas_Alsacargo/11_ohlvrf.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 97,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809622/Oficinas_Alsacargo/22_e1yhrj.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 98,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809622/Oficinas_Alsacargo/15_xzyaqd.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 99,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809620/Oficinas_Alsacargo/16_fhcmux.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 900,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809620/Oficinas_Alsacargo/13_pvf62k.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 901,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809619/Oficinas_Alsacargo/26_b1odde.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 902,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809618/Oficinas_Alsacargo/18_ornpce.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 903,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809617/Oficinas_Alsacargo/17_oi9zvf.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 904,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809616/Oficinas_Alsacargo/20_mnktqm.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 905,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809616/Oficinas_Alsacargo/19_dwauje.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 906,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809615/Oficinas_Alsacargo/3_xnhbjc.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 907,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809615/Oficinas_Alsacargo/1_xmamfa.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 908,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809614/Oficinas_Alsacargo/7_yrzg9u.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 909,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809613/Oficinas_Alsacargo/5_aipngd.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 9000,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809613/Oficinas_Alsacargo/8_rnmcy4.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 9001,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809612/Oficinas_Alsacargo/9_vjdsaj.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 9002,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809612/Oficinas_Alsacargo/25_q0nc1m.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 9003,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809611/Oficinas_Alsacargo/10_u89wdd.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 9004,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809610/Oficinas_Alsacargo/12_umxfaa.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
	{
		id: 9005,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809610/Oficinas_Alsacargo/23_tgfaop.jpg`,
		label: 'alsacargo',
		description: '',
		linkTo: '',
	},
];
