import { CLOUDINARY_IMG_PATH } from 'src/constants/paths';

export const OFICINAS_GA3 = [
	{
		id: 80,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1646908546/Oficinas_GrupoA3Arquitectos/A3Arq_opt_08_sia2fv.jpg`,
		label: 'grupo_A3_arquitectos',
		description: '',
		linkTo: '',
	},
	{
		id: 81,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1646908546/Oficinas_GrupoA3Arquitectos/A3Arq_opt_09_d8y6sj.jpg`,
		label: 'grupo_A3_arquitectos',
		description: '',
		linkTo: '',
	},
	{
		id: 82,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809565/Oficinas_GrupoA3Arquitectos/IMG_9937_E_laz71b.jpg`,
		label: 'grupo_A3_arquitectos',
		description: '',
		linkTo: '',
	},
	{
		id: 83,
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809565/Oficinas_GrupoA3Arquitectos/IMG_9952_E_b3shnt.jpg`,
		label: 'grupo_A3_arquitectos',
		description: '',
		linkTo: '',
	},
	{
		id: 84,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1646908546/Oficinas_GrupoA3Arquitectos/A3Arq_opt_10_jkf5wu.jpg`,
		label: 'grupo_A3_arquitectos',
		description: '',
		linkTo: '',
	},
	{
		id: 85,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1646908547/Oficinas_GrupoA3Arquitectos/A3Arq_opt_01_kshpkk.jpg`,
		label: 'grupo_A3_arquitectos',
		description: '',
		linkTo: '',
	},
	{
		id: 86,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1646908547/Oficinas_GrupoA3Arquitectos/A3Arq_opt_02_vfn9ka.jpg`,
		label: 'grupo_A3_arquitectos',
		description: '',
		linkTo: '',
	},
	{
		id: 87,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1646908547/Oficinas_GrupoA3Arquitectos/A3Arq_opt_03_smjhjb.jpg`,
		label: 'grupo_A3_arquitectos',
		description: '',
		linkTo: '',
	},
	{
		id: 88,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1646908546/Oficinas_GrupoA3Arquitectos/A3Arq_opt_05_asvzwa.jpg`,
		label: 'grupo_A3_arquitectos',
		description: '',
		linkTo: '',
	},
	{
		id: 89,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1646908546/Oficinas_GrupoA3Arquitectos/A3Arq_opt_07_b58jh9.jpg`,
		label: 'grupo_A3_arquitectos',
		description: '',
		linkTo: '',
	},
	{
		id: 800,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1646908546/Oficinas_GrupoA3Arquitectos/A3Arq_opt_10_jkf5wu.jpg`,
		label: 'grupo_A3_arquitectos',
		description: '',
		linkTo: '',
	},
];
