import { CLOUDINARY_IMG_PATH } from 'src/constants/paths';

export const PROJECTS = [
	{
		id: 1,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809151/Vivienda_RSM/10_x0x5nc.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '/projects/rsm_house',
	},
	{
		id: 2,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809039/Vivienda_FPM/14_a3es1h.jpg`,
		label: 'fpm_house',
		description: 'description',
		linkTo: '/projects/fpm_house',
	},
	{
		id: 3,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1652159060/Vivienda_VAM/VAM_1_vhcndv.jpg`,
		label: 'vam_house',
		description: 'description',
		linkTo: '/projects/vam_house',
	},
	{
		id: 4,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809468/Oficinas_Idai_Nature/02_ispkm2.jpg`,
		label: 'idai_nature',
		description: 'description',
		linkTo: '/projects/idai_nature',
	},
	{
		id: 5,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809072/Vivienda_PBM/01_hfsr8l.jpg`,
		label: 'pbm_house',
		description: 'description',
		linkTo: '/projects/pbm_house',
	},
	{
		id: 6,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808981/Vivienda_CRR/01_yfr7cf.jpg`,
		label: 'crr_house',
		description: 'description',
		linkTo: '/projects/crr_house',
	},
	{
		id: 7,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809565/Oficinas_GrupoA3Arquitectos/IMG_9929_E_em3iz7.jpg`,
		label: 'grupo_A3_arquitectos',
		description: 'description',
		linkTo: '/projects/grupo_A3_arquitectos',
	},
	{
		id: 8,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809366/Restaurante_Don_Mendo/Imagen_3_3_ay718c.jpg`,
		label: 'don_mendo',
		description: 'description',
		linkTo: '/projects/don_mendo',
	},
	{
		id: 9,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809432/Rehabilitacion_Iglesia/01_x5md8g.jpg`,
		label: 'church_tower',
		description: 'description',
		linkTo: '/projects/church_tower',
	},
	{
		id: 10,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808926/Vivienda_BGB/06_lhojqr.jpg`,
		label: 'bgm_house',
		description: 'description',
		linkTo: '/projects/bgm_house',
	},

	{
		id: 11,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808734/Vivienda_ANR/01_fphsx4.jpg`,
		label: 'anr_house',
		description: 'description',
		linkTo: '/projects/anr_house',
	},
	{
		id: 12,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809616/Oficinas_Alsacargo/20_mnktqm.jpg`,
		label: 'alsacargo',
		description: 'description',
		linkTo: '/projects/alsacargo',
	},
	{
		id: 13,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809321/Centro_Ocio_TorresPark/02_nkhisj.jpg`,
		label: 'torre_park',
		description: 'description',
		linkTo: '/projects/torre_park',
	},
];
