import { CLOUDINARY_IMG_PATH } from 'src/constants/paths';

export const PROJECTS = [
	{
		id: 1,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809151/Vivienda_RSM/10_x0x5nc.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '/projects/rsm_house',
	},
	{
		id: 2,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809039/Vivienda_FPM/14_a3es1h.jpg`,
		label: 'fpm_house',
		description: 'description',
		linkTo: '/projects/fpm_house',
	},
	{
		id: 3,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1652159060/Vivienda_VAM/VAM_1_vhcndv.jpg`,
		label: 'vam_house',
		description: 'description',
		linkTo: '/projects/vam_house',
	},
	{
		id: 4,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809468/Oficinas_Idai_Nature/02_ispkm2.jpg`,
		label: 'idai_nature',
		description: 'description',
		linkTo: '/projects/idai_nature',
	},
	{
		id: 5,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809072/Vivienda_PBM/01_hfsr8l.jpg`,
		label: 'pbm_house',
		description: 'description',
		linkTo: '/projects/pbm_house',
	},
	{
		id: 6,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808981/Vivienda_CRR/01_yfr7cf.jpg`,
		label: 'crr_house',
		description: 'description',
		linkTo: '/projects/crr_house',
	},
	{
		id: 7,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809565/Oficinas_GrupoA3Arquitectos/IMG_9929_E_em3iz7.jpg`,
		label: 'grupo_A3_arquitectos',
		description: 'description',
		linkTo: '/projects/grupo_A3_arquitectos',
	},
	{
		id: 8,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809366/Restaurante_Don_Mendo/Imagen_3_3_ay718c.jpg`,
		label: 'don_mendo',
		description: 'description',
		linkTo: '/projects/don_mendo',
	},
	{
		id: 9,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809432/Rehabilitacion_Iglesia/01_x5md8g.jpg`,
		label: 'church_tower',
		description: 'description',
		linkTo: '/projects/church_tower',
	},
	{
		id: 10,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808926/Vivienda_BGB/06_lhojqr.jpg`,
		label: 'bgm_house',
		description: 'description',
		linkTo: '/projects/bgm_house',
	},

	{
		id: 11,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808734/Vivienda_ANR/01_fphsx4.jpg`,
		label: 'anr_house',
		description: 'description',
		linkTo: '/projects/anr_house',
	},
	{
		id: 12,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809616/Oficinas_Alsacargo/20_mnktqm.jpg`,
		label: 'alsacargo',
		description: 'description',
		linkTo: '/projects/alsacargo',
	},
	{
		id: 13,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809321/Centro_Ocio_TorresPark/02_nkhisj.jpg`,
		label: 'torre_park',
		description: 'description',
		linkTo: '/projects/torre_park',
	},
	{
		id: 14,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721902616/Stadler_Training_Center/l8pnfxkqj7nz3dprz0sl.jpg`,
		label: 'stadler_training_center',
		description: 'description',
		linkTo: '/projects/stadler_training_center',
	},
	{
		id: 15,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721904401/Hotel_Restaurante/o0w3zketd8e8wph1m8i7.jpg`,
		label: 'restaurant_hotel',
		description: 'description',
		linkTo: '/projects/restaurant_hotel',
	},
	{
		id: 16,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721904510/Concurso_Campus_Tarongers/i2jguufm2whu5z4sa1zy.jpg`,
		label: 'campus_taronjers_contest',
		description: 'description',
		linkTo: '/projects/campus_taronjers_contest',
	},
	{
		id: 17,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721904201/Oficinas_Nules/kctbqdwzzboth418jbkj.png`,
		label: 'nules_offices',
		description: 'description',
		linkTo: '/projects/nules_offices',
	},
	{
		id: 18,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721905999/Vivienda_EBM/h1fenyg5a8op3hxekviw.png`,
		label: 'ebm_house',
		description: 'description',
		linkTo: '/projects/ebm_house',
	},
	{
		id: 19,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721902794/Perellonet/yjungvorza5tbgkircwg.jpg`,
		label: 'perellonet_house',
		description: 'description',
		linkTo: '/projects/perellonet_house',
	},
	{
		id: 20,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721906185/Concurso_Ayuntamiento_Albalat/qwzpfjsfbsbycntlkstp.jpg`,
		label: 'albalat_cityhall_cantest',
		description: 'description',
		linkTo: '/projects/albalat_cityhall_cantest',
	},
	{
		id: 21,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1721905536/Mueble_Valencia/xdelbqefc6euqcnjmwaf.jpg`,
		label: 'mueble_valencia',
		description: 'description',
		linkTo: '/projects/mueble_valencia',
	},
	{
		id: 22,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1722424027/XABEC/IMG_0793_slzkw3.jpg`,
		label: 'xabec',
		description: 'description',
		linkTo: '/projects/xabec',
	},
];
