import { CLOUDINARY_IMG_PATH } from 'src/constants/paths';

export const VIVIENDA_PBM = [
	{
		id: 50,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809072/Vivienda_PBM/06_o0zme3.jpg`,
		label: 'pbm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 51,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809072/Vivienda_PBM/07_ga2xqk.jpg`,
		label: 'pbm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 52,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809072/Vivienda_PBM/09_anbwgw.jpg`,
		label: 'pbm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 53,
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809072/Vivienda_PBM/01_hfsr8l.jpg`,
		label: 'pbm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 54,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809072/Vivienda_PBM/10_sly8ui.jpg`,
		label: 'pbm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 55,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809072/Vivienda_PBM/02_dgsy87.jpg`,
		label: 'pbm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 56,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809072/Vivienda_PBM/08_ayd770.jpg`,
		label: 'pbm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 57,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809072/Vivienda_PBM/03_qv7kks.jpg`,
		label: 'pbm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 58,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809072/Vivienda_PBM/05_j4jckl.jpg`,
		label: 'pbm_house',
		description: '',
		linkTo: '',
	},
	{
		id: 59,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809072/Vivienda_PBM/04_c45zhi.jpg`,
		label: 'pbm_house',
		description: '',
		linkTo: '',
	},
];
