export const TEAM = [
	{
		id: 1,
		path: '',
		imgUrl: `assets/img/miguel_angel.jpeg`,
		label: 'miguel_angel',
		description: 'description',
		linkTo: '',
	},
	{
		id: 2,
		path: '',
		imgUrl: `assets/img/Maria.jpeg`,
		label: 'maria_inmaculada',
		description: 'description',
		linkTo: '',
	},
	{
		id: 3,
		path: '',
		imgUrl: `assets/img/hector.jpeg`,
		label: 'hector',
		description: 'description',
		linkTo: '',
	},
	{
		id: 4,
		path: '',
		imgUrl: `assets/img/carles.jpeg`,
		label: 'carles',
		description: 'description',
		linkTo: '',
	},
	{
		id: 5,
		path: '',
		imgUrl: `assets/img/nacho.jpeg`,
		label: 'nacho',
		description: 'description',
		linkTo: '',
	},
	{
		id: 6,
		path: '',
		imgUrl: `assets/img/marina.jpeg`,
		label: 'marina',
		description: 'description',
		linkTo: '',
	},
	{
		id: 7,
		path: '',
		imgUrl: `assets/img/jorge.jpeg`,
		label: 'jorge',
		description: 'description',
		linkTo: '',
	},
	{
		id: 8,
		path: '',
		imgUrl: `assets/img/ines.jpeg`,
		label: 'ines',
		description: 'description',
		linkTo: '',
	},
];
