import { CLOUDINARY_IMG_PATH } from 'src/constants/paths';

export const VIVIENDA_RSM = [
	{
		id: 14,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809151/Vivienda_RSM/10_x0x5nc.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '',
	},
	{
		id: 15,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809150/Vivienda_RSM/01_pn34py.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '',
	},
	{
		id: 16,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809150/Vivienda_RSM/naquerabanner_ykccch.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '',
	},
	{
		id: 17,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809151/Vivienda_RSM/03_bhtjtm.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '',
	},
	{
		id: 18,
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809151/Vivienda_RSM/naqueraintbanner_ztowcv.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '',
	},
	{
		id: 19,
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809180/Vivienda_RSM/SAM_0321_q5uxoz.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '',
	},
	{
		id: 100,
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809152/Vivienda_RSM/15_psnvur.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '',
	},
	{
		id: 101,
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809152/Vivienda_RSM/06_paumdu.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '',
	},
	{
		id: 102,
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809152/Vivienda_RSM/12_gchutu.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '',
	},
	{
		id: 103,
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809151/Vivienda_RSM/07_zj9dxg.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '',
	},
	{
		id: 104,
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809151/Vivienda_RSM/14_e4kcpo.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '',
	},
	{
		id: 105,
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809151/Vivienda_RSM/16_ddt6mp.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '',
	},
	{
		id: 106,
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809151/Vivienda_RSM/02_zhqr3a.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '',
	},
	{
		id: 107,
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639809150/Vivienda_RSM/naquerabanner_ykccch.jpg`,
		label: 'rsm_house',
		description: 'description',
		linkTo: '',
	},
];
