import { CLOUDINARY_IMG_PATH } from 'src/constants/paths';

export const VIVIENDA_ANR = [
	{
		id: 70,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808734/Vivienda_ANR/01_fphsx4.jpg`,
		label: 'anr_house',
		description: '',
		linkTo: '',
	},
	{
		id: 71,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808660/Vivienda_ANR/02_blp5mr.jpg`,
		label: 'anr_house',
		description: '',
		linkTo: '',
	},
	{
		id: 72,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808660/Vivienda_ANR/10_gwrvgh.jpg`,
		label: 'anr_house',
		description: '',
		linkTo: '',
	},
	{
		id: 73,
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808660/Vivienda_ANR/07_bgvsab.jpg`,
		label: 'anr_house',
		description: '',
		linkTo: '',
	},
	{
		id: 74,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808660/Vivienda_ANR/06_djytkd.jpg`,
		label: 'anr_house',
		description: '',
		linkTo: '',
	},
	{
		id: 75,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808660/Vivienda_ANR/04_e0a94z.jpg`,
		label: 'anr_house',
		description: '',
		linkTo: '',
	},
	{
		id: 76,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808660/Vivienda_ANR/08_qvxifk.jpg`,
		label: 'anr_house',
		description: '',
		linkTo: '',
	},
	{
		id: 77,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808660/Vivienda_ANR/03_rqwqme.jpg`,
		label: 'anr_house',
		description: '',
		linkTo: '',
	},
	{
		id: 78,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808659/Vivienda_ANR/05_foppfh.jpg`,
		label: 'anr_house',
		description: '',
		linkTo: '',
	},
	{
		id: 79,
		path: '',
		imgUrl: `${CLOUDINARY_IMG_PATH}/v1639808659/Vivienda_ANR/09_ai9msn.jpg`,
		label: 'anr_house',
		description: '',
		linkTo: '',
	},
];
